#!/bin/sh
# Installs the mounted test client public key into ferry's authorized_keys
# (generated by start.sh, mounted read-only at /keys), then starts sshd in the
# foreground. Mirrors how atmoz/sftp picks up .ssh/keys, but for a full server.
set -e

mkdir -p /home/ferry/.ssh
if [ -f /keys/id_ed25519.pub ]; then
  cat /keys/id_ed25519.pub > /home/ferry/.ssh/authorized_keys
fi
chown -R ferry:ferry /home/ferry/.ssh
chmod 700 /home/ferry/.ssh
[ -f /home/ferry/.ssh/authorized_keys ] && chmod 600 /home/ferry/.ssh/authorized_keys

exec /usr/sbin/sshd -D -e
