import XCTest
@testable import FerryCore

/// SSH public-key authentication against the real Docker sshd (M11). The client
/// keypair is generated by testinfra/start.sh and its public half is authorized
/// on the server; here we log in with the private key.
final class SFTPKeyAuthTests: XCTestCase {
    private let port = Int(TestServers.sftpPort)

    override func setUp() async throws {
        _ = try TestServers.requireGreeting(port: TestServers.sftpPort, serverName: "SFTP")
    }

    /// TOFU-trusts the host key, then connects with the given credential.
    private func connectTrusting(_ credential: SSHAuthCredential) async throws -> SFTPSource {
        let store = TestServers.scratchHostKeyStore()
        func attempt() async throws -> SFTPSource {
            try await SFTPSource.connect(host: TestServers.host, port: port,
                                         username: TestServers.username,
                                         credential: credential,
                                         hostKeyStore: store)
        }
        do {
            return try await attempt()
        } catch let RemoteSourceError.hostKeyUnknown(info) {
            try store.trust(info, host: TestServers.host, port: port)
            return try await attempt()
        }
    }

    func testEd25519KeyLoginAndBrowse() async throws {
        guard let pem = TestServers.clientPrivateKey() else {
            throw XCTSkip("test client key missing — run testinfra/start.sh to generate it")
        }
        let source = try await connectTrusting(.privateKey(pem: pem, passphrase: nil))
        defer { Task { [source] in await source.disconnect() } }

        // Prove the authenticated session actually works.
        let home = try await source.homeDirectory()
        XCTAssertEqual(home, "/", "atmoz/sftp chroots the user to /")
        _ = try await source.list(directory: "/", includeHidden: false)
    }

    func testWrongKeyIsRejectedAsAuthFailure() async throws {
        // A syntactically valid key the server does not authorize.
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("ferry-wrongkey-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        let keyPath = dir.appendingPathComponent("id").path

        let keygen = Process()
        keygen.executableURL = URL(fileURLWithPath: "/usr/bin/ssh-keygen")
        keygen.arguments = ["-t", "ed25519", "-N", "", "-f", keyPath, "-q"]
        keygen.standardOutput = Pipe(); keygen.standardError = Pipe()
        try keygen.run(); keygen.waitUntilExit()
        try XCTSkipUnless(keygen.terminationStatus == 0, "ssh-keygen unavailable")

        let pem = try Data(contentsOf: URL(fileURLWithPath: keyPath))
        do {
            let source = try await connectTrusting(.privateKey(pem: pem, passphrase: nil))
            await source.disconnect()
            XCTFail("expected authentication failure for an unauthorized key")
        } catch RemoteSourceError.authenticationFailed {
            // expected
        }
    }
}
