import XCTest
@testable import FerryCore

/// M6 integration tests: SFTPSource against the real Docker SSH server
/// (atmoz/sftp on 127.0.0.1:2222; chrooted home "/", writable "upload/",
/// read-only fixtures at "/fixtures" — docs/TESTING.md).
final class SFTPSourceTests: XCTestCase {
    /// Must match testinfra/fixtures/seed/hello.txt exactly.
    private static let helloContents =
        "Hello from Ferry's test fixtures.\n" +
        "This file is seeded read-only into both test servers at fixtures/hello.txt.\n"

    private var source: SFTPSource!

    override func setUp() async throws {
        _ = try TestServers.requireGreeting(port: TestServers.sftpPort, serverName: "SFTP")
        source = try await TestServers.connectSFTP()
    }

    override func tearDown() async throws {
        await source?.disconnect()
        source = nil
    }

    func testConnectAndHomeDirectory() async throws {
        let home = try await source.homeDirectory()
        XCTAssertEqual(home, "/", "atmoz/sftp chroots the user to /")
    }

    func testWrongPasswordFailsAsAuthentication() async throws {
        await source.disconnect()
        do {
            _ = try await TestServers.connectSFTP(password: "definitely-wrong")
            XCTFail("expected authentication failure")
        } catch let error as RemoteSourceError {
            XCTAssertEqual(error, .authenticationFailed)
        }
    }

    func testListRootAndFixtures() async throws {
        let root = try await source.list(directory: "/", includeHidden: false)
        let upload = try XCTUnwrap(root.first { $0.name == "upload" })
        XCTAssertTrue(upload.isDirectory)
        XCTAssertEqual(upload.path, "/upload")

        let fixtures = try await source.list(directory: "/fixtures", includeHidden: false)
        let hello = try XCTUnwrap(fixtures.first { $0.name == "hello.txt" })
        XCTAssertFalse(hello.isDirectory)
        XCTAssertEqual(hello.size, Int64(Self.helloContents.utf8.count))
        XCTAssertNotNil(hello.permissions)
        XCTAssertNotNil(hello.modifiedAt)
    }

    func testStatFile() async throws {
        let item = try await source.stat(path: "/fixtures/hello.txt")
        XCTAssertEqual(item.name, "hello.txt")
        XCTAssertFalse(item.isDirectory)
        XCTAssertEqual(item.size, Int64(Self.helloContents.utf8.count))
    }

    func testListOnFileThrowsNotADirectory() async throws {
        await XCTAssertThrowsErrorAsync(
            try await self.source.list(directory: "/fixtures/hello.txt", includeHidden: true)) {
            XCTAssertEqual($0 as? FileSystemSourceError,
                           .notADirectory(path: "/fixtures/hello.txt"))
        }
    }

    func testMissingPathsThrowNotFound() async throws {
        await XCTAssertThrowsErrorAsync(try await self.source.stat(path: "/upload/nope.txt")) {
            XCTAssertEqual($0 as? FileSystemSourceError, .notFound(path: "/upload/nope.txt"))
        }
        await XCTAssertThrowsErrorAsync(
            try await self.source.openRead(at: "/upload/nope.txt", offset: 0)) {
            XCTAssertEqual($0 as? FileSystemSourceError, .notFound(path: "/upload/nope.txt"))
        }
    }

    func testDownloadWholeFile() async throws {
        var data = Data()
        for try await chunk in try await source.openRead(at: "/fixtures/hello.txt", offset: 0) {
            data += chunk
        }
        XCTAssertEqual(String(decoding: data, as: UTF8.self), Self.helloContents)
    }

    func testDownloadFromOffset() async throws {
        let offset = 34 // start of the second line
        var data = Data()
        for try await chunk in try await source.openRead(at: "/fixtures/hello.txt",
                                                         offset: Int64(offset)) {
            data += chunk
        }
        let expected = String(Self.helloContents.dropFirst(offset))
        XCTAssertEqual(String(decoding: data, as: UTF8.self), expected)
    }

    func testDownloadMultiChunkFileByteExact() async throws {
        // medium-1mb.bin is generated by testinfra/start.sh (1 MiB > several
        // 128 KiB read chunks). Compare against the local copy byte-exactly.
        let localURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // FerryIntegrationTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // FerryKit
            .deletingLastPathComponent()  // repo root
            .appendingPathComponent("testinfra/fixtures/seed/medium-1mb.bin")
        guard let local = try? Data(contentsOf: localURL) else {
            throw XCTSkip("medium-1mb.bin not generated yet — run testinfra/start.sh")
        }

        var remote = Data()
        for try await chunk in try await source.openRead(at: "/fixtures/medium-1mb.bin",
                                                         offset: 0) {
            remote += chunk
        }
        XCTAssertEqual(remote.count, local.count)
        XCTAssertEqual(remote, local, "downloaded bytes must match the seeded file exactly")
    }

    // MARK: Mutations (M10) — writable "/upload" only (atmoz/sftp chroot)

    /// Creates a file under /upload with the given bytes, replacing any leftover
    /// from a prior run.
    private func seedUploadFile(_ path: String, contents: String = "seed") async throws {
        try? await source.delete(at: path)
        let handle = try await source.openWrite(at: path, offset: 0)
        try await handle.write(Data(contents.utf8))
        try await handle.close()
    }

    func testRenameMovesFileAndRefusesClobber() async throws {
        let src = "/upload/rename-src.txt"
        let dst = "/upload/rename-dst.txt"
        let other = "/upload/rename-other.txt"
        try await seedUploadFile(src)

        try await source.rename(from: src, to: dst)
        _ = try await source.stat(path: dst)
        await XCTAssertThrowsErrorAsync(try await self.source.stat(path: src)) {
            XCTAssertEqual($0 as? FileSystemSourceError, .notFound(path: src))
        }

        // Renaming onto an existing path is refused (matches LocalFileSource).
        try await seedUploadFile(other)
        await XCTAssertThrowsErrorAsync(try await self.source.rename(from: dst, to: other)) {
            XCTAssertEqual($0 as? FileSystemSourceError, .alreadyExists(path: other))
        }

        try? await source.delete(at: dst)
        try? await source.delete(at: other)
    }

    func testRenameMissingSourceThrowsNotFound() async throws {
        let missing = "/upload/rename-missing-src.txt"
        let target = "/upload/rename-missing-dst.txt"
        try? await source.delete(at: missing)
        try? await source.delete(at: target)
        await XCTAssertThrowsErrorAsync(try await self.source.rename(from: missing, to: target)) {
            XCTAssertEqual($0 as? FileSystemSourceError, .notFound(path: missing))
        }
    }

    func testSetPermissionsRoundTrip() async throws {
        let path = "/upload/chmod-test.txt"
        try await seedUploadFile(path)

        try await source.setPermissions(FilePermissions(rawMode: 0o600), at: path)
        let locked = try await source.stat(path: path)
        XCTAssertEqual((locked.permissions?.rawMode ?? 0) & 0o777, 0o600)

        try await source.setPermissions(FilePermissions(rawMode: 0o644), at: path)
        let opened = try await source.stat(path: path)
        XCTAssertEqual((opened.permissions?.rawMode ?? 0) & 0o777, 0o644)

        try? await source.delete(at: path)
    }
}
