import FerryCore
import Foundation
import XCTest

/// Connection details for the local Docker test servers (see testinfra/).
/// Keep in sync with testinfra/docker-compose.yml.
enum TestServers {
    static let host = "127.0.0.1"
    static let sftpPort: UInt16 = 2222
    /// Exec-capable OpenSSH server for the SCP tests (M13). atmoz/sftp forbids
    /// exec and ships no scp binary, so SCP needs a full SSH server — see
    /// testinfra/ssh-exec and docs/DECISIONS.md ADR-020.
    static let scpPort: UInt16 = 2223
    static let ftpPort: UInt16 = 2121
    static let ftpsPort: UInt16 = 2990
    static let username = "ferry"
    static let password = "ferrypass"
    /// The SCP/SSH server's writable login directory; fixtures are mounted
    /// read-only at `<sshHome>/fixtures`.
    static let sshHome = "/home/ferry"
    /// The FTP servers' login directory (delfer/alpine-ftp-server). Fixtures are
    /// mounted read-only at `<ftpHome>/fixtures`; the home itself is writable.
    static let ftpHome = "/ftp/ferry"

    /// A throwaway HostKeyStore backed by a unique temp file, so a test's TOFU
    /// decisions never touch the real store or leak between tests.
    static func scratchHostKeyStore() -> HostKeyStore {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("ferry-test-known_hosts-\(UUID().uuidString)")
        return HostKeyStore(fileURL: url)
    }

    /// One store for the whole test process (unique file per run, so a
    /// recreated container's new host key never reads as CHANGED). Lets
    /// `connectSFTP` trust the server's key once and then connect with a single
    /// handshake — the extra TOFU round-trip on every connect otherwise tips the
    /// emulated sshd over its startup limit when the full suite runs.
    static let sharedHostKeyStore = HostKeyStore(fileURL: FileManager.default.temporaryDirectory
        .appendingPathComponent("ferry-test-shared-known_hosts-\(UUID().uuidString)"))

    /// The test client's private key, generated by testinfra/start.sh and
    /// authorized on the SFTP server. Nil if start.sh hasn't produced it yet.
    static func clientPrivateKey() -> Data? {
        // #filePath: …/FraSSH/FerryKit/Tests/FerryIntegrationTests/TestServers.swift
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // FerryIntegrationTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // FerryKit
            .deletingLastPathComponent()   // repo root
        let keyURL = repoRoot.appendingPathComponent("testinfra/fixtures/keys/id_ed25519")
        return try? Data(contentsOf: keyURL)
    }

    /// Opens a TCP connection and returns the server's greeting line,
    /// or nil if the port is unreachable. Synchronous on purpose —
    /// loopback connects resolve instantly and this avoids any
    /// continuation bookkeeping in test code.
    static func readGreeting(port: UInt16, timeoutSeconds: Int = 3) -> String? {
        let fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else { return nil }
        defer { close(fd) }

        var tv = timeval(tv_sec: timeoutSeconds, tv_usec: 0)
        setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, socklen_t(MemoryLayout<timeval>.size))

        var addr = sockaddr_in()
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = port.bigEndian
        addr.sin_addr.s_addr = inet_addr(host)
        let connected = withUnsafePointer(to: &addr) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                connect(fd, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard connected == 0 else { return nil }

        var buffer = [UInt8](repeating: 0, count: 256)
        let count = recv(fd, &buffer, buffer.count, 0)
        guard count > 0 else { return nil }
        return String(decoding: buffer[0..<count], as: UTF8.self)
    }

    /// Connects to the SFTP test server, transparently trusting the server's
    /// host key on first contact (TOFU). This mirrors what the app does after
    /// the user taps "Trust & Connect", so existing tests exercise the M11
    /// connect path without each managing a trust store. A wrong password still
    /// surfaces `.authenticationFailed`: the key is trusted first, then auth
    /// runs on the retry.
    static func connectSFTP(username: String = TestServers.username,
                            password: String = TestServers.password) async throws -> SFTPSource {
        let store = sharedHostKeyStore
        func attempt() async throws -> SFTPSource {
            do {
                return try await SFTPSource.connect(host: host, port: Int(sftpPort),
                                                    username: username,
                                                    credential: .password(password),
                                                    hostKeyStore: store)
            } catch RemoteSourceError.hostKeyUnknown(let info) {
                // First contact this run — trust once; later connects are single-handshake.
                try store.trust(info, host: host, port: Int(sftpPort))
                return try await SFTPSource.connect(host: host, port: Int(sftpPort),
                                                    username: username,
                                                    credential: .password(password),
                                                    hostKeyStore: store)
            }
        }
        // The emulated amd64 sshd drops connections under the cumulative load of
        // the full suite's ~50 reconnects (ADR-014); retry transient connection
        // failures generously. Auth failures are NOT retried — they surface
        // immediately so the wrong-password/wrong-key tests stay fast and exact.
        var lastError: Error?
        for _ in 0..<10 {
            do {
                return try await attempt()
            } catch let error as RemoteSourceError {
                if case .connectionFailed = error {
                    lastError = error
                    try? await Task.sleep(nanoseconds: 500_000_000)
                    continue
                }
                throw error
            }
        }
        throw lastError ?? RemoteSourceError.connectionFailed("exhausted retries")
    }

    /// Connects to the SCP/exec test server (:2223), trusting the host key on
    /// first contact (TOFU) exactly as `connectSFTP` does. Password auth by
    /// default; pass a `.privateKey` credential to exercise key auth. Retries
    /// transient connection failures, never auth failures.
    @available(macOS 15.0, *)
    static func connectSCP(username: String = TestServers.username,
                           credential: SSHAuthCredential = .password(TestServers.password)) async throws -> SCPSource {
        let store = sharedHostKeyStore
        func attempt() async throws -> SCPSource {
            do {
                return try await SCPSource.connect(host: host, port: Int(scpPort),
                                                   username: username, credential: credential,
                                                   hostKeyStore: store)
            } catch RemoteSourceError.hostKeyUnknown(let info) {
                try store.trust(info, host: host, port: Int(scpPort))
                return try await SCPSource.connect(host: host, port: Int(scpPort),
                                                   username: username, credential: credential,
                                                   hostKeyStore: store)
            }
        }
        var lastError: Error?
        for _ in 0..<10 {
            do {
                return try await attempt()
            } catch let error as RemoteSourceError {
                if case .connectionFailed = error {
                    lastError = error
                    try? await Task.sleep(nanoseconds: 500_000_000)
                    continue
                }
                throw error
            }
        }
        throw lastError ?? RemoteSourceError.connectionFailed("exhausted retries")
    }

    /// Connects to the plaintext FTP test server (:2121). Retries a transient
    /// connection failure a few times — vsftpd can briefly drop while the
    /// container settles — but never retries auth failures.
    static func connectFTP() async throws -> FTPSource {
        try await connectFTP(port: Int(ftpPort), security: .none)
    }

    /// Connects to the explicit-FTPS test server (:2990) with certificate
    /// verification off (the test cert is self-signed — ADR-019).
    static func connectFTPS() async throws -> FTPSource {
        try await connectFTP(port: Int(ftpsPort), security: .explicit,
                             allowInvalidCertificate: true)
    }

    /// Drives the REAL cert-trust path against :2990 (no `allowInvalidCertificate`
    /// hook): connects with no pin and returns the certificate the server offers,
    /// captured via the `.certificateUntrusted` error (ADR-033). Retries a
    /// transient connection failure while the container settles.
    static func captureFTPSCertificate() async throws -> CertificateInfo {
        var lastError: Error?
        for _ in 0..<5 {
            do {
                _ = try await FTPSource.connect(host: host, port: Int(ftpsPort),
                                                username: username, password: password,
                                                security: .explicit)
                throw RemoteSourceError.connectionFailed("expected an untrusted-certificate error")
            } catch let error as RemoteSourceError {
                if case .certificateUntrusted(let info) = error { return info }
                if case .connectionFailed = error {
                    lastError = error
                    try? await Task.sleep(nanoseconds: 500_000_000)
                    continue
                }
                throw error
            }
        }
        throw lastError ?? RemoteSourceError.connectionFailed("exhausted retries")
    }

    /// Connects to :2990 pinning `cert` — the real trust path (no
    /// `allowInvalidCertificate`). Retries a transient connection failure.
    static func connectFTPS(trusting cert: CertificateInfo) async throws -> FTPSource {
        var lastError: Error?
        for _ in 0..<5 {
            do {
                return try await FTPSource.connect(host: host, port: Int(ftpsPort),
                                                   username: username, password: password,
                                                   security: .explicit, trustedCertificate: cert)
            } catch let error as RemoteSourceError {
                if case .connectionFailed = error {
                    lastError = error
                    try? await Task.sleep(nanoseconds: 500_000_000)
                    continue
                }
                throw error
            }
        }
        throw lastError ?? RemoteSourceError.connectionFailed("exhausted retries")
    }

    static func connectFTP(port: Int, security: FTPSecurity,
                           allowInvalidCertificate: Bool = false,
                           username: String = TestServers.username,
                           password: String = TestServers.password) async throws -> FTPSource {
        var lastError: Error?
        for _ in 0..<5 {
            do {
                return try await FTPSource.connect(host: host, port: port,
                                                   username: username, password: password,
                                                   security: security,
                                                   allowInvalidCertificate: allowInvalidCertificate)
            } catch let error as RemoteSourceError {
                if case .connectionFailed = error {
                    lastError = error
                    try? await Task.sleep(nanoseconds: 500_000_000)
                    continue
                }
                throw error
            }
        }
        throw lastError ?? RemoteSourceError.connectionFailed("exhausted retries")
    }

    // MARK: Tunnels (M14)

    /// Ensures the SSH/exec server's (:2223) host key is trusted in the shared
    /// store, so a `TunnelEngine` (which connects its own session lazily) never
    /// hits a TOFU prompt. Uses the SFTP subsystem the exec container also
    /// exposes, so it works on macOS 14 (unlike the SCP path).
    static func trustSSHExecHostKey() async throws {
        let store = sharedHostKeyStore
        do {
            // Either the key is already trusted (connect succeeds) or this is
            // first contact (throws hostKeyUnknown → trust and we're done).
            let source = try await SFTPSource.connect(host: host, port: Int(scpPort),
                                                      username: username,
                                                      credential: .password(password),
                                                      hostKeyStore: store)
            await source.disconnect()
        } catch RemoteSourceError.hostKeyUnknown(let info) {
            try store.trust(info, host: host, port: Int(scpPort))
        }
    }

    /// A `TunnelEngine` pointed at the exec server (:2223), password auth,
    /// sharing the trusted host-key store. Call `trustSSHExecHostKey()` first.
    static func makeTunnelEngine() -> TunnelEngine {
        TunnelEngine(host: host, port: Int(scpPort), username: username,
                     credential: .password(password), hostKeyStore: sharedHostKeyStore)
    }

    /// Remote-forward round trip (M14.5): the in-container port the tests ask
    /// sshd to open via `tcpip-forward`, and the host-side port Docker maps to
    /// it (compose: 127.0.0.1:2224 → ssh container :18080). Keep in sync with
    /// testinfra/docker-compose.yml.
    static let remoteForwardServerPort = 18080
    static let remoteForwardHostPort: UInt16 = 2224

    /// Opens a TCP connection to `host:port` and keeps it open, returning the
    /// file descriptor (caller closes) — for live-connection-count tests.
    static func holdOpenConnection(port: UInt16) -> Int32? {
        let fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else { return nil }
        var addr = sockaddr_in()
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = port.bigEndian
        addr.sin_addr.s_addr = inet_addr(host)
        let connected = withUnsafePointer(to: &addr) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                connect(fd, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard connected == 0 else {
            close(fd)
            return nil
        }
        return fd
    }

    /// Binds a loopback socket to port 0, reads the OS-assigned port, and frees
    /// it — a race-tolerant way to pick a listen port for a tunnel test.
    static func freeLocalPort() -> UInt16 {
        let fd = socket(AF_INET, SOCK_STREAM, 0)
        defer { close(fd) }
        var addr = sockaddr_in()
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = 0
        addr.sin_addr.s_addr = inet_addr(host)
        _ = withUnsafePointer(to: &addr) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                bind(fd, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        var bound = sockaddr_in()
        var len = socklen_t(MemoryLayout<sockaddr_in>.size)
        _ = withUnsafeMutablePointer(to: &bound) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                getsockname(fd, $0, &len)
            }
        }
        return UInt16(bigEndian: bound.sin_port)
    }

    /// Drives a SOCKS5 CONNECT to `targetHost:targetPort` through the local
    /// proxy on `proxyPort`, returning the target's greeting (or nil on any
    /// framing failure). Synchronous raw sockets, like `readGreeting`.
    static func socksConnectGreeting(proxyPort: UInt16, targetHost: String, targetPort: UInt16,
                                     timeoutSeconds: Int = 4) -> String? {
        let fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else { return nil }
        defer { close(fd) }
        var tv = timeval(tv_sec: timeoutSeconds, tv_usec: 0)
        setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, socklen_t(MemoryLayout<timeval>.size))

        var addr = sockaddr_in()
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = proxyPort.bigEndian
        addr.sin_addr.s_addr = inet_addr(host)
        let connected = withUnsafePointer(to: &addr) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                connect(fd, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard connected == 0 else { return nil }

        func send(_ bytes: [UInt8]) -> Bool {
            bytes.withUnsafeBytes { Foundation.send(fd, $0.baseAddress, bytes.count, 0) == bytes.count }
        }
        func recv(_ count: Int) -> [UInt8]? {
            var buffer = [UInt8](repeating: 0, count: count)
            let n = Foundation.recv(fd, &buffer, count, 0)
            guard n == count else { return nil }
            return buffer
        }

        // Greeting → method selection.
        guard send([0x05, 0x01, 0x00]), let method = recv(2), method == [0x05, 0x00] else { return nil }
        // CONNECT request (IPv4).
        let octets = targetHost.split(separator: ".").compactMap { UInt8($0) }
        guard octets.count == 4 else { return nil }
        var request: [UInt8] = [0x05, 0x01, 0x00, 0x01]
        request += octets
        request += [UInt8(targetPort >> 8), UInt8(targetPort & 0xFF)]
        guard send(request), let reply = recv(10), reply[0] == 0x05, reply[1] == 0x00 else { return nil }

        var greeting = [UInt8](repeating: 0, count: 256)
        let n = Foundation.recv(fd, &greeting, greeting.count, 0)
        guard n > 0 else { return nil }
        return String(decoding: greeting[0..<n], as: UTF8.self)
    }

    /// Standard gate for every integration test: returns the greeting, or
    /// handles the servers-down case (skip locally, fail when
    /// FERRY_REQUIRE_TEST_SERVERS=1, e.g. in CI).
    static func requireGreeting(port: UInt16, serverName: String) throws -> String {
        if let greeting = readGreeting(port: port) { return greeting }
        let message = "\(serverName) test server is not reachable on port \(port). " +
                      "Start it with: testinfra/start.sh"
        if ProcessInfo.processInfo.environment["FERRY_REQUIRE_TEST_SERVERS"] == "1" {
            XCTFail(message)
            return ""
        }
        throw XCTSkip(message)
    }
}
