import FerryCore
import Foundation
import XCTest

/// Connection details for the local Docker test servers (see testinfra/).
/// Keep in sync with testinfra/docker-compose.yml.
enum TestServers {
    static let host = "127.0.0.1"
    static let sftpPort: UInt16 = 2222
    static let ftpPort: UInt16 = 2121
    static let username = "ferry"
    static let password = "ferrypass"

    /// A throwaway HostKeyStore backed by a unique temp file, so a test's TOFU
    /// decisions never touch the real store or leak between tests.
    static func scratchHostKeyStore() -> HostKeyStore {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("ferry-test-known_hosts-\(UUID().uuidString)")
        return HostKeyStore(fileURL: url)
    }

    /// One store for the whole test process (unique file per run, so a
    /// recreated container's new host key never reads as CHANGED). Lets
    /// `connectSFTP` trust the server's key once and then connect with a single
    /// handshake — the extra TOFU round-trip on every connect otherwise tips the
    /// emulated sshd over its startup limit when the full suite runs.
    static let sharedHostKeyStore = HostKeyStore(fileURL: FileManager.default.temporaryDirectory
        .appendingPathComponent("ferry-test-shared-known_hosts-\(UUID().uuidString)"))

    /// The test client's private key, generated by testinfra/start.sh and
    /// authorized on the SFTP server. Nil if start.sh hasn't produced it yet.
    static func clientPrivateKey() -> Data? {
        // #filePath: …/FraSSH/FerryKit/Tests/FerryIntegrationTests/TestServers.swift
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // FerryIntegrationTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // FerryKit
            .deletingLastPathComponent()   // repo root
        let keyURL = repoRoot.appendingPathComponent("testinfra/fixtures/keys/id_ed25519")
        return try? Data(contentsOf: keyURL)
    }

    /// Opens a TCP connection and returns the server's greeting line,
    /// or nil if the port is unreachable. Synchronous on purpose —
    /// loopback connects resolve instantly and this avoids any
    /// continuation bookkeeping in test code.
    static func readGreeting(port: UInt16, timeoutSeconds: Int = 3) -> String? {
        let fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else { return nil }
        defer { close(fd) }

        var tv = timeval(tv_sec: timeoutSeconds, tv_usec: 0)
        setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, socklen_t(MemoryLayout<timeval>.size))

        var addr = sockaddr_in()
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = port.bigEndian
        addr.sin_addr.s_addr = inet_addr(host)
        let connected = withUnsafePointer(to: &addr) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                connect(fd, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard connected == 0 else { return nil }

        var buffer = [UInt8](repeating: 0, count: 256)
        let count = recv(fd, &buffer, buffer.count, 0)
        guard count > 0 else { return nil }
        return String(decoding: buffer[0..<count], as: UTF8.self)
    }

    /// Connects to the SFTP test server, transparently trusting the server's
    /// host key on first contact (TOFU). This mirrors what the app does after
    /// the user taps "Trust & Connect", so existing tests exercise the M11
    /// connect path without each managing a trust store. A wrong password still
    /// surfaces `.authenticationFailed`: the key is trusted first, then auth
    /// runs on the retry.
    static func connectSFTP(username: String = TestServers.username,
                            password: String = TestServers.password) async throws -> SFTPSource {
        let store = sharedHostKeyStore
        func attempt() async throws -> SFTPSource {
            do {
                return try await SFTPSource.connect(host: host, port: Int(sftpPort),
                                                    username: username,
                                                    credential: .password(password),
                                                    hostKeyStore: store)
            } catch RemoteSourceError.hostKeyUnknown(let info) {
                // First contact this run — trust once; later connects are single-handshake.
                try store.trust(info, host: host, port: Int(sftpPort))
                return try await SFTPSource.connect(host: host, port: Int(sftpPort),
                                                    username: username,
                                                    credential: .password(password),
                                                    hostKeyStore: store)
            }
        }
        // The emulated amd64 sshd drops connections under the cumulative load of
        // the full suite's ~50 reconnects (ADR-014); retry transient connection
        // failures generously. Auth failures are NOT retried — they surface
        // immediately so the wrong-password/wrong-key tests stay fast and exact.
        var lastError: Error?
        for _ in 0..<10 {
            do {
                return try await attempt()
            } catch let error as RemoteSourceError {
                if case .connectionFailed = error {
                    lastError = error
                    try? await Task.sleep(nanoseconds: 500_000_000)
                    continue
                }
                throw error
            }
        }
        throw lastError ?? RemoteSourceError.connectionFailed("exhausted retries")
    }

    /// Standard gate for every integration test: returns the greeting, or
    /// handles the servers-down case (skip locally, fail when
    /// FERRY_REQUIRE_TEST_SERVERS=1, e.g. in CI).
    static func requireGreeting(port: UInt16, serverName: String) throws -> String {
        if let greeting = readGreeting(port: port) { return greeting }
        let message = "\(serverName) test server is not reachable on port \(port). " +
                      "Start it with: testinfra/start.sh"
        if ProcessInfo.processInfo.environment["FERRY_REQUIRE_TEST_SERVERS"] == "1" {
            XCTFail(message)
            return ""
        }
        throw XCTSkip(message)
    }
}
